### ISSUE TITLE
About P@N

### ISSUE THREAD

**Issue by FrankWork** [ppuliu/GloRE#2]
In your paper, the P@N of `PCNN+ATT` is 97.0. But I found the result reported in [other paper](https://arxiv.org/abs/1801.03603v1) is 86.0. Why your results is so high?

**Comment by ppuliu** [comment]
Hi Zhihui,

I'm not sure about the reason, but we have released our annotated predictions and you can find them at: https://github.com/ppuliu/GloRE/tree/master/results/manual.
